//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.08 at 09:17:31 PM CEST 
//


package com.dajevv.soap.loaneligibility;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Loan complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Loan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="holder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="amountLeft" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="noRates" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="noRatesLeft" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Loan", propOrder = {
        "holder",
        "totalAmount",
        "amountLeft",
        "noRates",
        "noRatesLeft"
})
public class Loan {

    @XmlElement(required = true)
    protected String holder;
    protected long totalAmount;
    protected long amountLeft;
    protected int noRates;
    protected int noRatesLeft;

    /**
     * Gets the value of the holder property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHolder() {
        return holder;
    }

    /**
     * Sets the value of the holder property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHolder(String value) {
        this.holder = value;
    }

    /**
     * Gets the value of the totalAmount property.
     */
    public long getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     */
    public void setTotalAmount(long value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the amountLeft property.
     */
    public long getAmountLeft() {
        return amountLeft;
    }

    /**
     * Sets the value of the amountLeft property.
     */
    public void setAmountLeft(long value) {
        this.amountLeft = value;
    }

    /**
     * Gets the value of the noRates property.
     */
    public int getNoRates() {
        return noRates;
    }

    /**
     * Sets the value of the noRates property.
     */
    public void setNoRates(int value) {
        this.noRates = value;
    }

    /**
     * Gets the value of the noRatesLeft property.
     */
    public int getNoRatesLeft() {
        return noRatesLeft;
    }

    /**
     * Sets the value of the noRatesLeft property.
     */
    public void setNoRatesLeft(int value) {
        this.noRatesLeft = value;
    }

}
